### ISSUE TITLE
Can Rush project structure and configuration file be supported?

### ISSUE THREAD

**Issue by a20185** [Thinkmill/manypkg#127]
As is written in `get-packages`，only yarn workspace & pnpm workspace configuration file is supported.
Would `rush.json` in Rush projects (monorepo) will be supported?

**Comment by elliot-nelson** [comment]
Fixed by https://github.com/Thinkmill/manypkg/pull/151, and released in latest version of manypkg!

I believe this issue can be closed (cc: @Andarist)

As an example, you can now do the following in a Rush monorepo:

```console
# Print all package files in the Rush monorepo
npx @manypkg/cli exec cat package.json
```
