### ISSUE TITLE
support/configure allowing `workspace:*`

### ISSUE THREAD

**Issue by juliusmarminge** [Thinkmill/manypkg#147]
Would it be possible to allow for `workspace:*` to be used as version?

I use this for internal packages that I don't publish in [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo). It works on main that is using npm but in [this PR where I'm migrating to PNPM](https://github.com/t3-oss/create-t3-turbo/pull/27) manypkg fails with [this error](https://app.warp.dev/block/4gItGcNTOGThzfmzTIv7tp).

**Comment by Stijnkool** [comment]
I am running into this issue as well.
```
error <package-a> has a dependency on <package-b>@workspace:* but the version
of <package-b> in the repo is 0.0.1 which is not within range of the depended on version,
please update the dependency version
```

**Comment by ColdSauce** [comment]
Running into this issue as well.

Quick mitigation on my end to ignore these errors:

```
manypkg check |& grep -v '@workspace'
```

Unfortunately, color is lost.

**Comment by hmans** [comment]
> Unfortunately, color is lost.

Also, `manypkg fix` will still overwrite these fields. :(

**Comment by theKashey** [comment]
This story started long long time ago https://github.com/Thinkmill/manypkg/issues/72
