### ISSUE TITLE
support asterix in upgrade

### ISSUE THREAD

**Issue by dohomi** [Thinkmill/manypkg#148]
Hello
I have an edge case where I would like to run 
```
manypkg upgrade mypackage *
```
to run and upgrade all `mypackage` to * because its part of the monorepo. Its an edge case because the `mypackage` name collides with the upgrade of another package with the same starting name.

Is that possible?

**Comment by dohomi** [comment]
I prepared a PR to support scoped package names ending with a "/" https://github.com/Thinkmill/manypkg/pull/175

**Comment by Andarist** [comment]
Closed by https://github.com/Thinkmill/manypkg/pull/206
