### ISSUE TITLE
Proposal: alternative approach to root dependencies

### ISSUE THREAD

**Issue by Noviny** [Thinkmill/manypkg#16]
Was talking about root dependencies. Manypkg breaks from its predecessor `bolt` in using versions within leaf* `package.json` files, and allowing them to be excluded from root AND that all dependencies in root must be listed under `dependencies`, not `devDependencies`

The benefits of the new approach:

- Calculable source of truth around package versions between packages
- packages become easier to remove - packages not used anywhere simply vanish
- shorter root package.jsons

The benefits of the old approach:

- single source of truth that can be referenced for what packages at what versions are installed

So question 1 then becomes "How important for repository maintainers is having a single source of truth of what packages at what versions exist entirely within the multi-package repository"

I've been talked around that having this single source of truth that is easy to reference is genuinely valuable.

There's an... alternate new approach if we want:

- single source of truth that can be referenced for what packages at what versions are installed
- packages become easier to remove - packages not used anywhere simply vanish

The new rules are:

1. All installed packages used in leaf packages must exist in `dependencies` in the root `package.json`
2. All installed packages not used in leaf packages must exist in `devDependencies` of the root

## Complaints with this approach

> This makes the tooling harder to understand, as it has more specific rule about where to place things

True, but we already have a lot of opinions, and things remain as easy to alert and fix as they currently are (thing mentioned in a package but not at root is a new fix, aligning versions changes slightly)

> people can throw everything in dev dependencies and then we are no better off

A risk, but also means people unconcerned with removing packages just don't care.

## Three possible decisions

1. Stick with what is in manypkg now, decide single source of truth for package versions is an okay trade-off
1a. Add a manypkg command to get this list, to counteract the trade-off
2. Revert to bolt's rules, add everything into dependencies still, decide removing unused packages being harder is an okay trade-off
3. Implement the new option proposed here, decide the added rules complexity is an okay trade-off. 

---

*New term - picked 'leaf' to match 'root' - may be bad. Technically we only have root and non-root, but that's not ideal either.

**Comment by mitchellhamilton** [comment]
> I've been talked around that having this single source of truth that is easy to reference is genuinely valuable.

I'd love to hear more about this, what it's used for, etc. I haven't personally found that as a thing I need but I assume this a Atlaskit and other things scale that makes it more useful?

>  1a. Add a manypkg command to get this list, to counteract the trade-off

Isn't this necessary for all three of the options? I would kinda argue it's more necessary because if I want to add a new dep on a package, I have to add it in two places with options 2 and 3 but only one with option 1.

**Comment by Noviny** [comment]
> I assume this a Atlaskit and other things scale that makes it more useful?

This. The use-case is effectively to help people who are maintaining a repository but aren't directly responsible for individual code. Atlaskit hits this a lot, but as noted, we don't as much because often the people maintaining the repository are very close with a lot of the code in the repository.

It's also in part a cost/benefit thing. Having a long list of root deps is low cost is an assumption.

> Isn't this necessary for all three of the options?

Assuming we're still adding `manypkg add`, my assumption is that it would take care of the double add, and `manypkg --fix` ends up with a tweaked behavior, but is equally solvable (it's what `bolt-check` is already doing I think)

I think of it as 'run one command to add in any of the three scenarios, fix does something different'.

On 1a specifically, if the list is just embedded in the root package.json, there's no reason to add a command to generate the list of all dependencies and their versions.

**Comment by mitchellhamilton** [comment]
> root deps thing

Would you have any examples of where they use it?

> Having a long list of root deps is low cost is an assumption.

I kind of think it might not be a good thing because I've been looking at https://pnpm.js.org as a thing that we might want to use(very much a probably not but maybe thing), largely because it's more strict about not letting workspaces access things that it doesn't actually depend on but not as "break the whole ecosystemy" in the way Yarn PnP is and having things in the root deps means anything can import it which is annoying because the ESLint rule isn't perfect for things like @babel/runtime because the import is written by a babel plugin.

> command thing

Whoops, sorry. I read it wrong and thought you meant we would only need an add command for option one. Makes sense.

**Comment by Noviny** [comment]
> it's more strict about not letting workspaces access things that it doesn't actually depend on

tbh, this is a huge win to me and worth keeping on track with our current approach. Will discuss more with Luke sometime but I think we don't want to pivot. The conclusion here is that things not at root is **not** low cost, even though it may appear low cost. It leads to a subtle annoying error class.

> Would you have any examples of where they use it?

Occasionally audits are done around pulling in multiple similar packages, or what the most bloat-iest packages in a repo are.

If a design-system is pulling in three different external select components, or has 4 ways to pull in lodash that means if `some-component` is rendered it pulls in all of lodash, AND something it depends in pulls in `lodash.snakecase` and some more nonsense like that, seeing these listed in the root allows you to do an 'aha, a thing to fix'.

Additional things is packages that people *keep adding* which you have banned from the repository (roll your own is lowish effort and package is way too heavy), this makes it clearly surfaced.

There's other things which you keep track of but it's not really where you're tracking them. A single react version for example is required, and the repo maintainer probably has strong opinions about what that is (and when upgrades happen). Since these lists are so long, it would be a nonsense to say that this is where the information for this 'lives'.

**Comment by mitchellhamilton** [comment]
So I think we’re happy with a command that lists all the deps and probably also a package to get it programmatically?

**Comment by Noviny** [comment]
Yep. Closing this and making that issue
