### ISSUE TITLE
Please restore Bolt support

### ISSUE THREAD

**Issue by steve-taylor** [Thinkmill/manypkg#172]
I realise Bolt didn't win the monorepo package manager war, but there are still people using it (e.g. me). For me, its killer features are enforcement of uniform dependency versions, speed and simplicity. I've tried them all and settled on a toolkit that included Bolt, Changesets and Manypkg.

Unfortunately, Changesets uses Manypkg to get workspaces, so Bolt support in Changesets is going away soon.

Can you please restore Bolt support? Alternatively, will you accept a well-crafted pull request that restores Bolt support?

**Comment by Andarist** [comment]
> Can you please restore Bolt support? Alternatively, will you accept a well-crafted pull request that restores Bolt support?

ye, i think you should be able to revert my PR that removed it

**Comment by steve-taylor** [comment]
Thanks! PR coming soon. While I'm at it, bolt seems to support exclusion patterns, whereas manypkg doesn't. So I'll fix that.
