### ISSUE TITLE
Bug: `npm:x@y` doesn't work for tags

### ISSUE THREAD

**Issue by KATT** [Thinkmill/manypkg#193]
Heya, super grateful for this lib, it keeps things tidy 🧹

In my case now, it seems to make things _too tidy_, where it doesn't allow me to use `@tag`

I added a dep in my monorepo for e.g. `"@trpc/server": "npm:@trpc/server@next",` (note it has a tag and not a version at the end). Manypkg does not like that.

```
☔️ error @examples/standalone-server has a dependency on @trpc/server@npm:@trpc/server@next but the version of @trpc/server in the repo is 10.45.0 which is not within range of the depended on version, please update the dependency version
```

See https://github.com/trpc/trpc/pull/5315:

![CleanShot 2024-01-11 at 21 34 01@2x](https://github.com/Thinkmill/manypkg/assets/459267/1d37195f-83f9-414c-b703-90005a4a456f)

**Comment by Andarist** [comment]
The most surprising thing for me here is that you say that it doesn't error like this with `npm@trpc/server@1.2.3` 😅 

Fixing this should be fairly easy [here](https://github.com/Thinkmill/manypkg/blob/7ef91be62b4871bc3f513bfc412d66ba8d923106/packages/cli/src/checks/INTERNAL_MISMATCH.ts#L25). Would you perhaps want to do it? 😉

**Comment by KATT** [comment]
Of course you're involved in this project, @Andarist, you're fucking everywhere 😂❤️

**Comment by Andarist** [comment]
The path from being a user to becoming a maintainer is surprisingly short at times 😅
