### ISSUE TITLE
`getPackages` fails when given a monorepo subdirectory instead of root directory.

### ISSUE THREAD

**Issue by manzoorwanijk** [Thinkmill/manypkg#200]
`getPackages` expects `dir` argument to be the monorepo root but its description says otherwise. 

https://github.com/Thinkmill/manypkg/blob/52d5dcb469b1d6781f56cff15b3556c8856ce8ca/packages/get-packages/src/index.ts#L26-L40

Structure:

```
├──📄 package.json
├──📁 packages
│	├──📁 pkg-a
│	│	├──📄 index.mjs
│	│	├──📄 package.json
│	├──📁 cli
│	│	├──📄 bin.mjs
│	│	├──📄 package.json
├──📁 apps
│	├──📁 app-a
│	│	├──📄 package.json
│	│	├──📁 src
```

- `cli` package is consumed by monorepo root

### Steps:
- Open Codesandbox Devbox - https://codesandbox.io/p/devbox/manypkg-get-packages-bug-5zdymd
- Sign in or download the devbox
- Install the dependencies - `yarn` or you can also set it up using `pnpm`
- In the root of the monorepo, run `yarn dev-cli`
- Verify the outfit from the CLI  package
- `cd packages/pkg-a` and run `yarn dev-cli` again

### Expected Behavior:
The command should be successful and should be able to output the monorepo packages

### Actual Behavior:
It throws an error - `TypeError: Cannot read properties of undefined (reading 'packages')`

Should it be

```ts
const monorepoRoot: MonorepoRoot = await findRoot(dir, options);
const packages: Packages = await monorepoRoot.tool.getPackages(monorepoRoot.rootDir);
//                                                             ^^^^^^^^^^^^^^^^^^^^
```
instead of

```ts
const monorepoRoot: MonorepoRoot = await findRoot(dir, options);
const packages: Packages = await monorepoRoot.tool.getPackages(dir);
//                                                             ^^^
```

**Comment by Andarist** [comment]
The proposed solution sounds plausible. We'd appreciate a PR with this fix and the appropriate test case.

**Comment by manzoorwanijk** [comment]
> The proposed solution sounds plausible. We'd appreciate a PR with this fix and the appropriate test case.

Sure, I will try to create one.
