### ISSUE TITLE
Can't specify URL Tarball, instead of semver range, for dependencies

### ISSUE THREAD

**Issue by scottsidwell** [Thinkmill/manypkg#37]
## Background 
We have a dependency entry in our root package.json, and package-a/package.json, that directly links to a tarball, e.g.:
```
{
  ...
  "dependencies": {
    ...
    "bootstrap": "https://github.com/twbs/bootstrap/archive/v3.3.5.tar.gz"
    ...
  }
}
```

## Actual Behaviour
When running `yarn manypkg check` we see it fail with the following error

```
☔️ error TypeError: Invalid comparator: https://github.com/twbs/bootstrap/archive/v3.3.5.tar.gz
☔️ error     at Comparator.parse (/my-monorepo/node_modules/sembear/node_modules/semver/semver.js:794:11)
☔️ error     at new Comparator (/my-monorepo/node_modules/sembear/node_modules/semver/semver.js:777:8)
☔️ error     at Range.<anonymous> (/my-monorepo/node_modules/sembear/node_modules/semver/semver.js:975:12)
☔️ error     at Array.map (<anonymous>)
☔️ error     at Range.parseRange (/my-monorepo/node_modules/sembear/node_modules/semver/semver.js:974:13)
☔️ error     at Range.<anonymous> (/my-monorepo/node_modules/sembear/node_modules/semver/semver.js:917:17)
☔️ error     at Array.map (<anonymous>)
☔️ error     at new Range (/my-monorepo/node_modules/sembear/node_modules/semver/semver.js:916:40)
☔️ error     at upperBound (/my-monorepo/node_modules/sembear/dist/sembear.cjs.dev.js:19:11)
☔️ error     at /my-monorepo/node_modules/sembear/dist/sembear.cjs.dev.js:138:19
```

## Expected Behaviour
manypkg check should gladly accept [tarball urls](https://docs.npmjs.com/files/package.json#urls-as-dependencies) if they are consistent across the package.jsons in the repo.

In the case where there is a mix of tarball urls or semver ranges, it should return a warning that it couldn't reconcile the versions in the repo.

## Hypothesis
It looks like sembear is assuming that it will be able to coerce the range into a valid value. I'm guessing we should do a check as to whether a dependency version is valid semver or not, and avoid trying to coerce it.

**Comment by Noviny** [comment]
Hey! Thanks for reporting this.

I'm going to work on solving this now. @mitchellhamilton I am basically going to go with the rule that non-standard dependency specifications (not semver) shall be treated as requiring an exact match of the string, and will be working on a fix for this now. Will hopefully get a PR up for it in the next few days.

Ping me if you disagree with this approach.

**Comment by Noviny** [comment]
NB: This is probably going to be an error that can't be manually fixed. There is possibly something clever we can do with a CI to pick between possible options but probs not going to do that for MVP

**Comment by efoken** [comment]
Just having the same issue here. I added an Expo app to my monorepo which needs the following dependency:

```json
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
```
