### ISSUE TITLE
sembear fails when trying to compare a git version type

### ISSUE THREAD

**Issue by maraisr** [Thinkmill/manypkg#65]
When a package dep references github directly, the checker fails. I believe its got something to do with:

https://github.com/Thinkmill/manypkg/blob/a4db72a8b272f1b642fa751639d7840f4fa3658c/packages/cli/src/checks/utils.ts#L112

That being said - I have started to raise a pr that simply ignores `git:` but then it dawned on me that this'll also be an issue for `file:` etc... So I'm opening up the issue to discuss a best approach.

I believe that perhaps we can simply wrap that `highest` call in a try catch, so if it throws we could simply move on? Perhaps there is a way to first detect if its a semver version string, and if so only then check it.

I do accept that this is probably not best practice in using git, file and so on - references but there have been times where I'd want to still have the level of strictness manypkg offer, but not semever. Also I'd say that this wouldnt be verifiying that the strings are greater or less than - perhaps manypkg could error if the strings it finds aren't equal, ie: `"packageA": "git://github.com/abc/xyz.git#master"` is not the same as `"packageA": "git://github.com/abc/xyz.git#random-hash"`.

**Comment by mitchellhamilton** [comment]
I think this makes sense. Let's check if the specifier is a range and if it's not, it should be treated as the highest "range", if there are multiple non-range specifiers, the one chosen doesn't matter though it should be consistent(do a .sort() on them).

**Comment by maraisr** [comment]
Thanks for the response @mitchellhamilton 

Do you mind elaborating a bit more on your approach? I must admit, I'm a tad confused.

Do you mean if its a range thing (how do i detect this?), then highest wins out. If its a file/git reference, then its merely a warning if its different?

**Comment by mitchellhamilton** [comment]
Detecting a valid range can happen with `validRange` from `semver`.

Manypkg does not and likely will never have any concept of warnings because warnings create lots of problems. Instead, Manypkg opts to error and auto-fix.

What I'm proposing is essentially that `getHighestExternalRanges` would be implemented like this. (the name is really wrong because it's package specifiers, not strictly ranges but I'm just trying to show the idea)

```tsx
export let getHighestExternalRanges = weakMemoize(function getHighestVersions(
  allPackages: Map<string, Package>
) {
  let externalSpecifiers = new Map<string, Set<string>>();
  for (let [pkgName, pkg] of allPackages) {
    for (let depType of NORMAL_DEPENDENCY_TYPES) {
      let deps = pkg.packageJson[depType];
      if (deps) {
        for (let depName in deps) {
          if (!allPackages.has(depName)) {
            let specifiers = externalSpecifiers.get(depName);
            if (!specifiers) {
              specifiers = new Set();
              externalSpecifiers.set(depName, specifiers);
            }
            specifiers.add(deps[depName]);
          }
        }
      }
    }
  }
  let highestExternalSpecifiers = new Map<string, string>();
  for (let [depName, _specifiers] of externalSpecifiers) {
    let specifiers = [..._specifiers].sort();
    let nonRangeSpecifier = specifiers.find((x) => !semver.validRange(x));
    if (nonRangeSpecifier) {
      highestExternalSpecifiers.set(depName, nonRangeSpecifier);
    } else {
      highestExternalSpecifiers.set(depName, highest(specifiers));
    }
  }
  return highestExternalSpecifiers;
});
```
